# This is a basic workflow that is manually triggered

name: Subtree Push

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  pull_request:
    types:
      - closed
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  subtree-push:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    # Runs a single command using the runners shell
    - name: Checkout Repository
      uses: actions/checkout@v4 
      with:
        token: ${{ secrets.ACTION_TOKEN }}
        fetch-depth: 0
    - name: Git subtree push
      uses: dongmin-ra/git-subtree
      with:
        pat: ${{ secrets.ACTION_TOKEN }}
        repo:  https://github.com/dongmin-ra/subtree_test_slave.git
        action: push
        prefix: lib
        #- name: Git Config
        #run: |
        #git config --global user.email "test@test.com"
        #git config --global user.name "test_bot"
        #git config --global url.https://api:${{ secrets.ACTION_TOKEN }}@github.com/.insteadOf https://github.com/
        #git config --unset-all http.https://github.com/.extraheader
        #- name: Subtree push
        #run: |
        #git subtree push --prefix lib https://github.com/dongmin-ra/subtree_test_slave.git main
