# This is a basic workflow that is manually triggered

name: Subtree Push

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  pull_request:
    types:
      - closed
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  subtree-push:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    # Runs a single command using the runners shell
    - name: Checkout Repository
      uses: actions/checkout@v2 
    - name: subtree sync
      uses: jmadler/git-subtree-action@1.0
      with:
        github_token: ${{ secrets.ACTION_TOKEN }}
        action: 'push'
        repo: 'https://github.com/dongmin-ra/subtree_test_slave.git' 
        position: 'main'
        prefix: 'lib'
